UI Imrpvements
digabi/naksu pull request #56
Opened 2021-05-22 19:55 UTC by developerfromjokela

Added user-friendly message (with translations) for MEB Share directory error and added progress dialog for installing/updating the ktp server.

2021-05-28 10:50 UTC, visadb requested changes
Kiitos pull requestista! Hyvä parannus, enkä keksi itse toteutuksesta mitään purnattavaa.

Inline-kommentteina pikkuhuomioita, ja erityisesti asioita, joista meidän lintteri valittaa. Harmillisesti ulkopuolisille pull requesteille ei näemmä ajeta meidän github-checkejä, joten lintterivirheet eivät näy kovin selvästi. Lintteri ajautuu esim. komennolla `make docker`, jonka jälkeen voi tutkia tiedostoja `checkstyle-linux.xml` ja `checkstyle-windows.xml`.

2021-05-28 10:50 UTC, visadb commented on src/naksu/ui/progress/dialog.go
> +)
Go-koodauskonvention mukaan importit tulevat järjestykeen 1) stdlib, 2) kolmannen osapuolen kirjastot 3) tämän projektin muut moduulit, ja nämä kolme ryhmää pitää erottaa tyhjällä rivillä:

```suggestion
import (
	"strconv"

	"github.com/andlabs/ui"

	"naksu/xlate"
)
```

2021-05-28 10:50 UTC, visadb commented on src/naksu/mebroutines/install/install.go
> +	updateProg("Removing temporary raw image file", 100*(3/3))
CheckStyle (gocritic) valittaa tästä: "dupSubExpr: suspicious identical LHS and RHS for `/` operator". Eli ilmeisesti se ei tykkää tuosta `3/3`-subexpressionista. Tykkään tästä selkeästä `100*(2/3)`-tyylistä, mutta ehkäpä nämä voisi silti kirjoittaa auki gocriticin lepyttämiseksi: `33`, `67` ja `100`.

2021-05-28 10:50 UTC, visadb commented on src/naksu/ui/progress/dialog.go
> +}
Tätä funktiota ei käytetä, ja se näyttäisi täysin identtiseltä funktion `TranslateAndUpdateProgressDialogWithMessage` kanssa. Pitäisikö `TranslateAndUpdateProgressDialog` siis vain poistaa?

2021-05-28 10:50 UTC, visadb commented on res/gettext/fi.po
>  msgid "Uncompressing image: %d %%"
Tämä `"Uncompressing image: %d %%"`-viesti jäi orvoksi, joten sen voisi poistaa.

2021-05-28 10:50 UTC, visadb commented on src/naksu/mebroutines/install/install.go
> +	updateProg := func(message string, value int) {
Selkeyttäisin tän nimeä, `updateProg` -> `updateProgress` tai ehkä jopa `updateProgressDialog`. Mun pää halusi ensin tulkita `Prog`-lyhenteen ensin sanaksi Program, mikä vähän hämäsi.

2021-05-29 20:42 UTC, developerfromjokela commented on src/naksu/ui/progress/dialog.go
> +}
Ajattelin sen olevan siinä mahdollista myöhempää käyttöä varten, jos UIta tekee, niin ehkäpä sitä tarvitsee jossain muualla.

2021-05-31 06:15 UTC, developerfromjokela commented
Nyt checkstyle ei anna varoituksia :smiley:

2021-05-31 08:15 UTC, visadb approved these changes

2021-05-31 08:16 UTC, merged